from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.graph import StateGraph
from langchain.prompts import PromptTemplate
from langchain_core.messages import HumanMessage,AIMessage,BaseMessage
from langchain_core.tools import tool
from typing import TypedDict,Optional
from pydantic import BaseModel,Field
import asyncio
from dotenv import load_dotenv

load_dotenv()

#TypedDist for tracking the internal state at Compile_Runtime Safety
class user(TypedDict):
    input:str
    output:Optional[str]|None=None

#BaseModel for strictly validate the LLM output at Runtime
class output(BaseModel):
    llm_output:str=Field(description="Validating the output generated by LLM")

#Calculater
@tool(description="Perform the mathematical operations as per the user input.")
async def calculator(state:user)->user:
    """Perform mathematical Calculation """
    





